M48
; DRILL file {KiCad 8.0.1} date 2025-01-10T19:22:28-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-10T19:22:28-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X141.122Y-62.535
T2
X125.374Y-69.444
M30
